### ISSUE TITLE
Update filename from 'MicrosoftWebDriver.exe' to 'msedgedriver'

### ISSUE THREAD

**Issue by aruiz-futurefinance** [RafalSkorka/wdio-edgedriver-service#1]
- It looks in the time since this service was created, MS has changed the name of the driver from `MicrosoftWebDriver.exe` to `msedgedriver.exe`
  - https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

- Is it also possible to add a check for the OS used
```
command = process.platform === 'win32' ? 'msedgedriver.exe' : 'msedgedriver';
```
  - This will help if/when https://github.com/sitespeedio/edgedriver/issues/1 is also resolved

I can raise a PR if it helps

**Comment by RafalSkorka** [comment]
Please check if it works now for you, then I'll release a new npm package.
